---
- name: Install required packages
  apt:
    name: postgresql
    state: present
    update_cache: true

- name: Install psycopg2 package
  become: yes
  apt:
    name: python3-psycopg2
    state: present
    update_cache: yes
