replicaCount: 1
image:
    repository: 913524929706.dkr.ecr.eu-north-1.amazonaws.com/itsyndicate/week8
    tag: latest
containerPort: 8000
host: ex.com
certManager:
    enabled: false
    email: ex@gmail.com
    privateKeySecret: letsencrypt-prod
    clusterIssuerName: letsencrypt-prod
config:
    allowedHosts: '*'
secrets:
    databaseUrl: ENC[AES256_GCM,data:WrIacOji/6igmkyuq51sOHn5gk+O3oZLZE117ivWzNYHzPdW8mom5hMOhvVWRvY5wp3kAGAV3w3eWGT/54Uxx+rN8IB8OIepBc0mW+go/kc4XgMo2oKI1VGGB8tdA53NRVYKRFqRc3vqgXRb8AiFKT1X8dxzT4a2rHI5L+n5,iv:ce/IzMsVTtPxEaQwOE9vIoquxD6XMgbWdoN+pR0Dn7M=,tag:Na++sgAEfe8Pz7DFiFq8QA==,type:str]
    username: ENC[AES256_GCM,data:pmBP2uFsETHT,iv:VhxA01812X6Z8JDxye/jItYcx+ysSKq7RgRKTMABPxc=,tag:69/SGHJa5DhuNh39XotmCg==,type:str]
    password: ENC[AES256_GCM,data:KCCrmgiCKBY=,iv:wgbweaTgVIL6qROIRNjCkzq8FZqZooJMVw61/KeW0Lk=,tag:dAgItXhFcvFXEs5auiIdLw==,type:str]
    secretKey: ENC[AES256_GCM,data:8tVgtfTjd4u4,iv:60HfmVWgybjhDdkUtQ5XGH0vFzPwLYDW0gg9fr7MqDg=,tag:xSl4MU8HLUg9+l5aH7MARw==,type:str]
hpa:
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
sops:
    age:
        - recipient: age1ts0ykttetm8frdxsstt8jktjc8hmpy2fkj0e0zxml0j4cwx0hy8s03sz94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUmRvOUJYVmtEQzJFdVdB
            dGx0bDRWb1FCNmNiR0trS09KV0grRDczenlVCllLcDlWeHovRXduRG9GdEdnRlpz
            TCsxTUxqSm1CR01qVXRSejlLU2VsKzgKLS0tIDlSb0N3WTMvd1cvZFhZVytsZW1R
            QnNkMkVwWW9la2phcTBjR2lLOUx3RGMK6KgUwyS4UCSS+oAgrX6V7+9FswXlWcPy
            8D6lpEizO8oa41BvS4Ds9s5Lrf1+p71PcxqIh2zr1WFyri2ALZU2qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T09:02:46Z"
    mac: ENC[AES256_GCM,data:iMOsmVsVOy5sWEkWXC44LDKrJNeRwNVuGNrw4/IdhciSJpz5WuaR+Y5JWEJavplptAIlHOR1VMit72OtmLa3f5YsiGWikjewtwkfY/pEFV7LAY14UL0AJRFLqaM+E3xDyJ9hjM1ixqeaWpGnhfZTrdJzo9Lgvp8k1/LVtAxsRGY=,iv:5ZqGndzdQMTa7wtdg/XJU1shQMGMjI4bcD59oGx8JN4=,tag:ngSHB+tQ2ydCeeJnk2P7bQ==,type:str]
    encrypted_regex: ^(databaseUrl|username|password|secretKey)$
    version: 3.10.2
