replicaCount: ENC[AES256_GCM,data:PA==,iv:Ou+72/NCHut4B522L/JKwqq+RvUXm4MaKtUZFuFeCBU=,tag:iugNg48uTsKndePaebDIpQ==,type:int]
image:
    repository: ENC[AES256_GCM,data:nFy004D0Cy7M/Eo2XnkdD4BqACl4aQCHxrjspR++dTvNshAIrryRJ2TPkEBAOVNae8S580lLY66A5EXDu6VF,iv:oJd40DOuRFZOnXMorHvG1R4PDlk3/8aN5tQ1Tx2gwtc=,tag:O5A1+D0QUkcr2HzETi7QdQ==,type:str]
    tag: ENC[AES256_GCM,data:fzfp4o+x,iv:2TYVoky/N8ek638ofT96nJ1sXy73TY8gu634VvQOJAo=,tag:o7NquRjyPcl3MReTHtTQTw==,type:str]
containerPort: ENC[AES256_GCM,data:GS2XDw==,iv:EmWbwu8CigtaUgWWahP5UeUoyyYLZLgWklzAQmao7To=,tag:05s6IvV7ob81oSOuJ+wSVQ==,type:int]
host: ENC[AES256_GCM,data:9dCMhUhL,iv:LRHFUrNDG5eCfhiR+QwtlhqsSkFrLk2nurf5SKcAQ0w=,tag:DCCbhrrV3sFZF5o1WYPZpg==,type:str]
certManager:
    enabled: ENC[AES256_GCM,data:5zpoXKw=,iv:de6xpxkvvtWeAmOfFuqIMqfIYb0i/S+Z5wObWfpmDO4=,tag:q51RwUULiVb9fB2nRK1iiA==,type:bool]
    email: ENC[AES256_GCM,data:eMS9RtsWYCTOyknX,iv:sizp7eHZOQwrfG2WZb47pfDESehWcQqyAbxpkSniJ0A=,tag:Y8xf+aYEmm2V6GvYNNo+tg==,type:str]
    privateKeySecret: ENC[AES256_GCM,data:hQz8MykgXtH1yR4jVsfr3A==,iv:pD/dqMlytsZJV0TT01376UXXECSt/ftgtHcBjSCUOmM=,tag:c6OXvvW2CTSUOI++vVPeXQ==,type:str]
    clusterIssuerName: ENC[AES256_GCM,data:2jHH+UeAFPNfYtZmygmVIw==,iv:AQF/5vRKiz28wn6qGjDExqpXqXTNrx07inxHNTibi0A=,tag:MKwlEDzewaGaYs1IfjX9uw==,type:str]
config:
    allowedHosts: ENC[AES256_GCM,data:CA==,iv:dPzf3GpJ3hArs9MvoSqtu3RFY1Qn5P8mEjMCztUBqKk=,tag:+CXi3C7Vtdc0hM+coUc/Tw==,type:str]
secrets:
    databaseUrl: ENC[AES256_GCM,data:9PXm0oa2IUQApRF6fxLPVAPqj77DUcRXRfmuVVQ4TCMCb+PRPIueR3iakiuNvgV6XVNhYhgDIC7HYMDmbZiIvkE+fNqjET12+5IxC1xz/1KXnjc5+nWhsHTpx7XMV0yjzU5a2HbmooT0o6wWYbW9S17rdt03MwU8lDpRrKzq,iv:1eLIGqV9pTjECpXPVM74JhrioTqfXbDZPfm6Ft1EVfE=,tag:w+FoGJ/Sb4YwvtUGa82lbQ==,type:str]
    username: ENC[AES256_GCM,data:oTZBeUBiCyCm,iv:Yvfp8K48vlEkiPZx0FHyOMRPNBJEHqUQJ7VqqmDKw/Q=,tag:1rJYd2A/XTeGmWDT2JuO7w==,type:str]
    password: ENC[AES256_GCM,data:90cMp+6Wqfg=,iv:58TSly7pW5VabC38KZsx54quQoax6Jav3bfmoKTHZTo=,tag:vsIz95IO0tWQYlehf13qjA==,type:str]
    secretKey: ENC[AES256_GCM,data:ow9s93/BSEoL,iv:SgvlNqUu+D5Ca3mFA4SM4lbUKAtXcLTX4vuh1O6bDUk=,tag:az0uj/E8BVC/iHWJ+gm0jA==,type:str]
hpa:
    minReplicas: ENC[AES256_GCM,data:kQ==,iv:yzZEkhJoePHszc6m/pExKj7pUovZGx1bfgGEhwaIwb4=,tag:ZjJ6CrbmzaqjFN+fz1V+zA==,type:int]
    maxReplicas: ENC[AES256_GCM,data:iQ==,iv:YmLStQVDuViS5hzgLxjhh5UieL8Z2wIt2+ACCEiafSk=,tag:EdBJ3qy6AN6fplouZs7Uug==,type:int]
    targetCPUUtilizationPercentage: ENC[AES256_GCM,data:Hm0=,iv:OWPztsAwBsLaZ+Tf3V1wNsXdlvmOBlR/8Wwf/IdqB60=,tag:qxaN+dJY1m4g4zN5kQGOTQ==,type:int]
sops:
    age:
        - recipient: age1ts0ykttetm8frdxsstt8jktjc8hmpy2fkj0e0zxml0j4cwx0hy8s03sz94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRkw4K3hTYytxWXZOYVN3
            NXhsMEhmNVVKTEhXL0dQVGlLbldrWVp6NkcwCjlkSjl4bjViZTg4a2RZanc3bUpO
            OTJ3Q3B0c0w1d1lqY2Q5MnpJdzFJYmsKLS0tIDNlWk9BVW1wQldkY3ZFa3Zpc0cw
            MmZGMlZ5YndDV3RhQkNLR0d1aTFNZzQK2PWzRsViIqfFZV7M80Le7IzYCUR9241d
            SwKwbmEt8tExul4H0wyw1DO2qIZE3/m/S/xiNVIvhpb3pYAdePbQ7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T08:56:58Z"
    mac: ENC[AES256_GCM,data:fhEgZVf1WYYW2Ev81Nz+B2xNskWAJcV+OwGecwcWBDWnQK6KBW+yY7JpMlFdnBRDgiKzk/uhEbw3WGP7G0FPcz+Cdku1hi02zkSTQmrsWZDt2CU8bTvxI8JdW+YURjttNj08rnNOciON3fVlIG5qcEiX9z8ww+4IC0MJwGpHOlU=,iv:rZ1waPgOcCEgruHkEKc2dS0lVGJyAwBPWiWgeYiCYEc=,tag:Ymy0rYuH7X9mNwHSHeW6fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
